name = "ewald2p_recip"
version = "0.1.0"
license = "MIT"
maintainer = "Jin Nakazono"
author = "Jin Nakazono"
copyright = "Copyright 2026, Jin Nakazono"
description = "Fortran library for the reciprocal-space part of the neutral 2-periodic Ewald sum for Coulomb point charges."

[build]
auto-executables = false
auto-examples = false
auto-tests = true
module-naming = false

[install]
library = true
